### PR TITLE
[PE] Colliders Editor module fixes and code improvements.

### LINKED ISSUE #117: kkpe: enable new dynamic bones forgets all bones of objects when off
when the option to enable new dynamic bones is unchecked, upon saving and loading the scene every object with its own bones will have them disabled. characters preserve their bones' on/off state, but ex. sos cock (soft) will have both of its bones turned off every time.

### PR DESCRIPTION
**Pull request by ShalltyB**
- Fixed problem where some colliders with the new option didn't load properly.
- Fixed an old bug where colliders couldn't be imported/duplicated properly.
- Added an identifier for load sessions so objects can keep track of each other between load types (Load/Import/External).

This closes #117

### CODE REVIEW

File: Core.PoseEditor/MainWindow.cs [hunk 1]
```diff
@@ -40,6 +40,9 @@ public class MainWindow : MonoBehaviour
     {
         #region Public Static Variables
         internal static MainWindow _self;
+
+        public static int _lastLoadId = 0;
+        public static LoadType _lastLoadType = LoadType.None;
```
Comment (ManlyMarco) [inline Core.PoseEditor/MainWindow.cs]: Do both of those need to be public? Looks like they should be internal instead.

Comment (ShalltyB) [reply Core.PoseEditor/MainWindow.cs]: not necessarily but I was leaving it public so other plugins can use it along with ExternalLoadScene()

**Review by ManlyMarco — APPROVED** [review]
